ip: 192.168.83.130
port: 9999
thread_num: 5
max_channel_num: 10000
log_name: imagine_zooKeeper_profile.yaml
log_path: /home/imagine/MIT6824/Imagine_ZooKeeper/config/
max_log_file_size: 104857600
async_log: false
singleton_log_mode: false
log_title: Imagine ZooKeeper
log_with_timestamp: true